version: "3.9"
services:
  grafana:
#    image: grafana/grafana-arm32v7-linux:latest
    image: grafana/grafana:10.1.2-ubuntu
    ports:
      - 3000:3000
  prometheus:
    image: prom/prometheus-linux-armv7:v2.32.1
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
  postgres:
    image: arm32v7/postgres
    ports:
      - 5432:5432
    volumes:
      - ./backup:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: shop
  postgres-exporter:
    image: prometheuscommunity/postgres-exporter
    ports:
      - 9187:9187
    environment:
      DATA_SOURCE_NAME: "postgresql://postgres:postgrespassword@postgres:5432/shop?sslmode=disable"
    links:
      - postgres
      - prometheus
